import { useState, useEffect } from 'react'
import { Button } from '../ui/Button'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const minus = () => {
    if (count > 0) setCount(count - 1)
  }

  const add = () => setCount(count + 1)

  useEffect(() => {
    chrome.storage.sync.get(['count'], (result) => {
      setCount(result.count || 0)
    })
  }, [])

  useEffect(() => {
    chrome.storage.sync.set({ count })
    chrome.runtime.sendMessage({ type: 'COUNT', count })
  }, [count])

  return (
    <main className="min-h-[320px] w-[320px] p-6 bg-gradient-to-br from-[#4338ca] via-[#6366f1] to-[#1e1b4b] text-white relative overflow-hidden">
      {/* Background gradient overlay to match screenshot */}
      <div className="absolute inset-0 bg-gradient-to-b from-[#4338ca]/80 via-[#6366f1]/60 to-[#1e1b4b] -z-10" />
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_rgba(139,92,246,0.4)_0%,_transparent_50%)] -z-10" />
      {/* Central spotlight effect */}
      <div className="absolute left-1/2 top-2/5 transform -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-gradient-radial from-blue-400/10 via-purple-400/5 to-transparent blur-3xl opacity-90 pointer-events-none" />
      
      <div className="relative z-10 max-w-[280px] mx-auto">
        <header className="flex items-center gap-3 mb-6">
          <span className="text-md font-bold">Browser.AI</span>
          <span className="h-2 w-2 rounded-full bg-green-400 animate-pulse" />
        </header>

        <h1 className="text-3xl font-bold mb-2 bg-gradient-to-r from-white to-white/80 bg-clip-text text-transparent">Good Morning !</h1>
        <p className="text-white/70 mb-6">Initializing your task, Hang tight!</p>

        <div className="flex justify-center items-center gap-4 mb-6">
          <Button variant="outline" size="icon" onClick={minus} disabled={count <= 0}>
            -
          </Button>
          <div className="text-xl font-semibold flex items-center min-w-[2ch] justify-center">{count}</div>
          <Button variant="outline" size="icon" onClick={add}>
            +
          </Button>
        </div>

        <a href={link} target="_blank" className="text-xs text-white/50 hover:text-white/70 transition-colors block text-center">
          generated by create-chrome-ext
        </a>
      </div>
    </main>
  )
}

export default Popup
