name: Elite SaaS CI

on:
  push:
    branches: [ "main", "feat/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r elite_saas/backend/requirements.txt
        pip install ruff  # Install our linter

    - name: Lint with ruff
      run: |
        ruff check elite_saas/backend/
        ruff format --check elite_saas/backend/

    # - name: Test with pytest
    #  run: |
    #    pytest